language: java
jdk:
    - openjdk8
branches:
    only:
        - stable
deploy:
    # Github Releases
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: build/libs/HypixelUtils-*.*.*.jar
      skip_cleanup: true
      draft: true
#      on:
#          tags: true
install: skip
script: ./gradlew build
