branches:
    only:
        - /release-v[0-9].[0-9].[0-9]/
#        - stable

language: java
jdk:
    - openjdk8

install: skip
script:
    - ./gradlew build
    - rm --verbose ./build/libs/HypixelUtils-*.*.*-sources.jar

deploy:
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: build/libs/HypixelUtils-*.*.*.jar
      skip_cleanup: true
      draft: true
      on:
          tags: true
#          branch: stable
