language: java
jdk:
    - openjdk8

install: skip
script: ./gradlew build

branches:
    only:
        - /release-v[0-9].[0-9].[0-9]/
#        - stable

deploy:
    # Github Releases
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: build/libs/HypixelUtils-*.*.*.jar
      skip_cleanup: true
      draft: true
      on:
          tags: true
#          branch: stable
